routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
    return redirect('/login');
});

Route::get('registro','Auth\RegisterController@showRegistrationForm');
Route::post('registro',['as' => 'registro','uses' => 'Auth\RegisterController@register']);

Auth::routes(['register' => false,'verify' => true]);

app/Models/User.php
<?php

namespace App\Models;

use App\Notifications\{ResetPassword,VerifyEmail};
use Illuminate\Contracts\Auth\{MustVerifyEmail,CanResetPassword};
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class User extends Authenticatable implements MustVerifyEmail,CanResetPassword
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'legajo','nombre','apellido','email','dni','password','tipo','estado','genero'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmail); // my notification
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }

    public function mustCompleteData() : bool
    {
        if ($this->legajo > 0 && $this->nombre != '' && $this->apellido != '' && $this->dni != '' && $this->email != '') {
            return false;
        }

        return true;
    }

    public function getNombreCompletoAttribute()
    {
        return $this->nombre." ".$this->apellido;
    }

    public function esAdministrador()
    {
        return $this->tipo === 1;
    }



}

resources/views/layouts/page-content/footer.blade.php
<div class="footerbar">
    <footer class="footer">
        <p class="mb-0">{{ date("Y")}} {{ env('APP_NAME') }} - Todos los derechos reservados.</p>
    </footer>
</div>

resources/views/layouts/page-content/mobile.blade.php
<!-- Start Topbar Mobile -->
<div class="topbar-mobile">
    <div class="row align-items-center">
        <div class="col-md-12">
            <div class="mobile-logobar">
                <a href="{{url('/')}}" class="mobile-logo"><img src="assets/images/logo.svg" class="img-fluid" alt="logo"></a>
            </div>
            <div class="mobile-togglebar">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item">
                        <div class="topbar-toggle-icon">
                            <a class="topbar-toggle-hamburger" href="javascript:void();">
                                <img src="assets/images/svg-icon/horizontal.svg" class="img-fluid menu-hamburger-horizontal" alt="horizontal">
                                <img src="assets/images/svg-icon/verticle.svg" class="img-fluid menu-hamburger-vertical" alt="verticle">
                            </a>
                        </div>
                    </li>
                    <li class="list-inline-item">
                        <div class="menubar">
                            <a class="menu-hamburger" href="javascript:void();">
                                <img src="assets/images/svg-icon/menu.svg" class="img-fluid menu-hamburger-collapse" alt="collapse">
                                <img src="assets/images/svg-icon/close.svg" class="img-fluid menu-hamburger-close" alt="close">
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/page-content/notifications.blade.php
<!--
<li class="list-inline-item">
    <div class="notifybar">
        <div class="dropdown">
            <a class="dropdown-toggle infobar-icon" href="#" role="button" id="notoficationlink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="assets/images/svg-icon/notifications.svg" class="img-fluid" alt="notifications">
                <span class="live-icon">2</span></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="notoficationlink">
                <div class="notification-dropdown-title">
                    <h4>Notifications</h4>
                </div>
                <ul class="list-unstyled">
                    <li class="media dropdown-item">
                        <span class="action-icon badge badge-success-inverse">N</span>
                        <div class="media-body">
                            <h5 class="action-title">New trends for you</h5>
                            <p><span class="timing">10 min ago</span></p>
                        </div>
                    </li>
                    <li class="media dropdown-item">
                        <span class="action-icon badge badge-primary-inverse"><i class="feather icon-gift"></i></span>
                        <div class="media-body">
                            <h5 class="action-title">John birthday today</h5>
                            <p><span class="timing">Today, 12:00 AM</span></p>
                        </div>
                    </li>
                    <li class="media dropdown-item">
                        <span class="action-icon badge badge-warning-inverse">T</span>
                        <div class="media-body">
                            <h5 class="action-title">This is start of your story</h5>
                            <p><span class="timing">Yesterday, 01:25 PM</span></p>
                        </div>
                    </li>
                    <li class="media dropdown-item">
                        <span class="action-icon badge badge-danger-inverse"><i class="feather icon-thumbs-up"></i></span>
                        <div class="media-body">
                            <h5 class="action-title">Admin has 1 new like</h5>
                            <p><span class="timing">5 Feb 2020, 03:31 PM</span></p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</li>
-->

resources/views/layouts/page-content/open-close-menu.blade.php
<div class="togglebar" id="toggle-menu">
    <ul class="list-inline mb-0">
        <li class="list-inline-item">
            <div class="menubar">
                <a class="menu-hamburger" href="javascript:void();">
                    <img id="menu-opened" src="{{ asset('assets/images/svg-icon/menu.svg') }}" class="img-fluid menu-hamburger-collapse" alt="menu">
                    <img id="menu-closed" src="{{ asset('assets/images/svg-icon/close.svg') }}" class="img-fluid menu-hamburger-close" alt="close">
                </a>
            </div>
        </li>
        </li>
    </ul>
</div>

resources/views/layouts/page-content/page-content.blade.php
<div class="rightbar">
    @include('layouts.page-content.top-menu')
    <!-- End Topbar -->
    <div class="breadcrumbbar"  style="margin-bottom: 50px">
        @yield('content')
    </div>
    <!-- Start Footerbar -->
    @include('layouts.page-content.footer')
    <!-- End Footerbar -->
</div>

resources/views/layouts/page-content/profile.blade.php
<li class="list-inline-item">
    <div class="profilebar">
        <div class="dropdown">
            <a class="dropdown-toggle" href="#" role="button" id="profilelink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @if((Auth::user()->genero === 'femenino'))
                    <img src="{{ asset('assets/images/users/girl.svg')}}" class="img-fluid" alt="profile">
                @else
                    <img src="{{ asset('assets/images/users/boy.svg')}}" class="img-fluid" alt="profile">
                @endif
                <span class="live-icon">{{ Auth::user()->nombre_completo }}</span>
                <span class="feather icon-chevron-down live-icon"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="profilelink">
                <div class="dropdown-item">
                    <div class="profilename">
                        <h5>{{ Auth::user()->nombre_completo }}</h5>
                    </div>
                </div>
                <div class="userbox">
                    <ul class="list-unstyled mb-0">
                        <li class="media dropdown-item">
                            <a href="{{ route('profile') }}" class="profile-icon"><img src="{{ asset('assets/images/svg-icon/crm.svg') }}" class="img-fluid" alt="user">Mi perfil</a>
                        </li>
                        <li class="media dropdown-item">
                            <a href="{{ route('logout') }}" class="profile-icon" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><img src="{{ asset('assets/images/svg-icon/logout.svg') }}" class="img-fluid" alt="logout">Cerrar sesión</a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>

                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</li>

resources/views/layouts/page-content/top-menu.blade.php
{{-- @include('layouts.page-content.mobile') --}}
<!-- Start Topbar -->
<div class="topbar">
    <!-- Start row -->
    <div class="row align-items-center">
        <!-- Start col -->
        <div class="col-md-12 align-self-center">
            @include('layouts.page-content.open-close-menu')
            <div class="infobar">
                <ul class="list-inline mb-0">
                    @include('layouts.page-content.notifications')
                    @include('layouts.page-content.profile')
                </ul>
            </div>
        </div>
        <!-- End col -->
    </div>
    <!-- End row -->
</div>